def build_strategy(project,research):
    client=project.get("client","Client"); goal=project.get("goal","Grow qualified demand"); industry=project.get("industry","Other")
    answers=[x for x in project.get("discovery_answers",[]) if x.get("answer")]; supplied=project.get("strategy_context","")
    facts=[]
    if research.get("title"): facts.append({"source":"Verified Research","label":"Website title","value":research["title"]})
    if research.get("description"): facts.append({"source":"Verified Research","label":"Website description","value":research["description"]})
    for h in research.get("h1",[])[:4]: facts.append({"source":"Verified Research","label":"Website heading","value":h})
    if goal: facts.append({"source":"Client-Provided","label":"Primary goal","value":goal})
    if project.get("budget"): facts.append({"source":"Client-Provided","label":"Budget","value":project["budget"]})
    if supplied: facts.append({"source":"Account Manager / Client Context","label":"Strategy context supplied at intake","value":supplied[:4000]})
    for item in answers: facts.append({"source":"AI Gap Check","label":item.get("question","Gap input"),"value":item.get("answer","")})

    base={
      "Digital Media":{"objective":"Capture existing demand while creating incremental awareness and qualified consideration.","opportunity":"Connect high-intent search behavior with broader audience development so paid media supports both immediate conversion and future demand.","response":"Use an integrated paid-media system in which Search captures intent, Performance Max expands conversion opportunities, Paid Social develops targeted demand, and Performance Media / CTV extends qualified reach.","tactics":["Google Search","Performance Max","Paid Social","Performance Media / CTV"],"rationale":"Each channel has a distinct role; investment should follow business priority, audience intent, geography and measurable conversion opportunity.","investment_role":"Primary performance and scalable reach investment.","outcome":"More qualified visibility, traffic and measurable conversion activity tied to the business goal.","success":"Digital performance KPIs: qualified conversions, CPA/CPL, conversion rate, calls/leads and ROAS when defensible revenue inputs exist."},
      "SEO / AEO":{"objective":"Increase discoverability across traditional search and AI-assisted discovery.","opportunity":"Build durable visibility around priority services, expertise, locations and high-value questions audiences are actively researching.","response":"Combine technical/on-page SEO, priority-page optimization, local search, expert-reviewed content and AI-search optimization into one organic visibility program.","tactics":["Technical + on-page audit","Priority-page optimization","Local SEO","Expert-reviewed content","AI-search visibility"],"rationale":"Paid media captures demand while SEO/AEO compounds discoverability and authority over time.","investment_role":"Long-term visibility and authority investment.","outcome":"Stronger organic discovery and a larger qualified search footprint.","success":"Organic visibility, priority rankings, qualified organic traffic/conversions, local visibility and AI-search presence."},
      "Organic Social":{"objective":"Build visible brand relevance, trust and ongoing audience engagement.","opportunity":"Turn the organization’s people, expertise, work and proof points into a consistent social presence rather than relying on service advertising alone.","response":"Define platform roles and content pillars, increase short-form video, highlight authentic people/proof and actively manage the community.","tactics":["Platform roles","Content pillars","Short-form video","Community management"],"rationale":"Organic social should make the brand feel active, credible and human while supporting broader campaign narratives.","investment_role":"Always-on brand and community support.","outcome":"Greater reach, engagement, audience growth and content depth.","success":"Reach, engagement, follower/community growth, video consumption and qualitative audience response."},
      "Production":{"objective":"Create the visual assets required to make the integrated strategy credible and distinctive.","opportunity":"Replace generic or repetitive creative with owned visual storytelling that can work across paid, organic, web and PR.","response":"Develop a modular content library combining hero storytelling, vertical video, photography and expert/leadership interviews.","tactics":["Hero brand story","Vertical video","Photography","Expert / leadership interviews"],"rationale":"Strong production increases the usefulness and longevity of every downstream marketing channel.","investment_role":"Shared content infrastructure supporting multiple departments.","outcome":"A reusable asset library that improves campaign quality and consistency.","success":"Approved deliverables, asset utilization across channels, production efficiency and content longevity."},
      "Creative / Website":{"objective":"Turn campaign attention into a clear, credible and low-friction conversion experience.","opportunity":"Align creative messaging and landing experiences with the audience intent generated by media, search, social and PR.","response":"Strengthen conversion paths, landing pages, differentiation/proof, campaign creative and tracking readiness.","tactics":["Conversion paths","Landing pages","Proof + differentiation","Tracking"],"rationale":"Media performance is constrained when the post-click experience does not clearly answer why the audience should act.","investment_role":"Conversion infrastructure and campaign enablement.","outcome":"Clearer user journeys and stronger conversion readiness.","success":"Launch completion, UX improvements, conversion-path quality, asset performance and measurable website actions."},
      "PR / Communications":{"objective":"Build third-party credibility and extend the strategy through earned visibility.","opportunity":"Translate organizational expertise, milestones and differentiated stories into narratives that matter beyond owned channels.","response":"Develop focused story lanes, thought leadership and proactive media outreach aligned with the broader marketing calendar.","tactics":["Story lanes","Thought leadership","Media outreach"],"rationale":"Earned credibility can strengthen awareness and trust in ways paid and owned channels cannot replicate alone.","investment_role":"Credibility, reputation and earned-awareness support.","outcome":"Stronger authority and external visibility around priority narratives.","success":"Quality placements, relevant coverage, message pull-through, thought-leadership opportunities and referral visibility."}
    }
    sections={}
    for name,d in base.items():
        sections[name]={**d,"recommendations":d["tactics"]}
    context=(" Supplied account/client context has been incorporated as a primary strategy input." if supplied else "")
    if answers: context+=" AI gap-check inputs were incorporated where provided."
    executive=f"{client} needs an integrated {industry.lower()} marketing strategy built around one business objective: {goal}. The recommended approach connects brand visibility, demand creation, intent capture, conversion infrastructure, organic authority and credibility so each PMC discipline has a defined role in the same growth system.{context}"
    narrative={"opportunity":f"Build a coordinated marketing system for {client} that turns awareness and credibility into measurable action around {goal}.","challenge":"Avoid fragmented channel activity by giving each PMC discipline a specific strategic role, shared priorities and an integrated measurement approach.","strategic_response":"Use paid, owned, earned and organic channels as one connected system: create demand, capture intent, convert interest and compound authority over time."}
    return {"executive":executive,"narrative":narrative,"facts":facts,"departments":{k:v["recommendations"] for k,v in sections.items()},"department_sections":sections}
